#!/bin/bash

# directory that contains your git repositories
devdir="$HOME/Development"

# connectivity check
ping -q -w 1 -c 1 "$(ip r | grep default | tail -1 | cut -d ' ' -f 3)" >/dev/null || exit

# fingers crossed that people are sane and their directories doesn't contain whitespaces
repos=$(find $devdir -name .git -type d)

# common part of git rev command executed for both origin and upstream
gitrev="git rev-list --left-only --count"

for repo in $repos
do
	# we hop into the repository and fetch all remotes (can be pretty slow *shrug*)
	cd $repo/..; git fetch --all >/dev/null 2>&1

	# get origin "diff" and if upstream is present, get that one too
	org=$($gitrev origin/master...@)
	ups=$(git remote -v | cut -f 1 | grep -q upstream && $gitrev upstream/master...@)

	# format the output into "repository_name[origin_ahead(|upstream_ahead)]"
	[[ $ups -ne 0 ]] && upstr="|$ups" || upstr=""
	[[ $org -ne 0 || $upstr ]] && found+=" ${PWD##*/}($org$upstr)"
done

echo -n $found
